
const mediaData = {
  new: [
    { id:"0030", title: "Queen - Bohemian Rhapsody", image: "media/bohemian-rapsody.jpg", summary: "A genre-blending rock epic that follows a man's emotional turmoil as he confronts guilt, fate, and inner conflict." },
    { id: "0002", title: "The Last of Us", image: "media/the-last-of-us.png", summary: "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope." },
    { id: "0025", title: "Where Winds Meet", image: "media/wwm.jpg", summary: "An open-world action RPG set in ancient China where a wandering swordsman uncovers political secrets and shapes his own legend." },
    { id: "0014", title: "The Dark Knight", image: "media/dark-knight.jpg", summary: "Batman faces his greatest moral test when the Joker unleashes chaos across Gotham, forcing him to choose between justice and sacrifice." },
    { id: "0020", title: "Avatar: The Last Airbender", image: "media/atla.jpg", summary: "Aang, the last Airbender and only surviving Avatar, must master all four elements to stop a devastating war and restore balance." },
    { id: "0038", title: "The False Prince", image: "media/tfp.jpg", summary: "Several orphan boys are forced into a dangerous competition to impersonate a missing prince, but one contestant uncovers a deadly conspiracy." },
    { id: "0017",title: "The Matrix", image: "media/matrix.jpg", summary: "A hacker discovers that reality is a simulated world controlled by machines, pushing him to join a rebellion fighting for humanity’s freedom." },
  ],
    
  popular: {
    movies: [
      { id: "0004", title: "Interstellar", image: "media/interstellar.jpg", summary: "A team of explorers travels through a wormhole in search of a new home for humanity as Earth faces collapse." },
      { id: "0005", title: "Inception", image: "media/inception.jpg", summary: "A skilled thief enters people’s dreams to steal secrets, but his toughest mission requires planting an idea deep within a target’s mind." },
      { id: "0014", title: "The Dark Knight", image: "media/dark-knight.jpg", summary: "Batman struggles to stop the Joker’s reign of terror as Gotham descends into chaos and moral boundaries blur." },
      { id: "0015", title: "Twelve Angry Men", image: "media/12-angry-men.jpg", summary: "Twelve jurors debate the fate of a young defendant, revealing biases and tensions as they seek the truth." },
      { id: "0016", title: "Fight Club", image: "media/fight-club.jpg", summary: "A disillusioned man forms an underground fight club, sparking a radical movement that spirals far beyond his control." },
      { id: "0001", title: "Dune: Part Two", image: "media/dune-part-two.png", summary: "After the massacre of house atreides the son of the late duke Leto atreides Paul and his mother lady Jessica travel with the fremen and learn their ways. While Paul starts getting closer to the fremen girl Chani the rest of the fremen either despise him or worship him as the Lisan al Gaib. Paul is torn between his compassion for Chani and the desire to lead the fremen as their messiah. Meanwhile the Baron Harkonnen recovering from his wounds takes control over arrakis away from Rabban and gifts it to his psychotic nephew Feyd Rautha Harkonnen. Paul is left with the choice of staying at his current position with the fremen or rising up as the Lisan al gaib and challenging the emperor and house harkonnen." },
      { id: "0018", title: "Spiderman: Across the spiderverse", image: "media/spiderman-atsv.jpg", summary: "Miles Morales journeys across multiple universes, encountering new Spider-heroes while confronting a threat that could unravel the multiverse." },
      { id: "0017",title: "The Matrix", image: "media/matrix.jpg", summary: "A hacker learns his world is a simulation and joins a rebellion fighting against machine domination." },

      // These need images still:
      // { id: "0035", title: "The Godfather", image: "media/godfather.png", summary: "The Corleone family navigates loyalty, betrayal, and power in Coppola’s iconic crime saga." },
      // { id: "0036", title: "The Shawshank Redemption", image: "media/shawshank.png", summary: "Two prisoners forge a bond and cling to hope in the face of injustice." },
      // { id: "0037", title: "Pulp Fiction", image: "media/pulp-fiction.png", summary: "Tarantino’s nonlinear crime drama intertwines gangsters, hitmen, and chance encounters." },
      // { id: "0038", title: "Forrest Gump", image: "media/forrest-gump.png", summary: "A simple man’s extraordinary journey through decades of American history and love." },
      // { id: "0039", title: "Titanic", image: "media/titanic.png", summary: "A romance blossoms aboard the doomed ocean liner in James Cameron’s sweeping drama." },
      // { id: "0040", title: "Star Wars: A New Hope", image: "media/star-wars.jpngpg", summary: "Luke Skywalker joins the Rebel Alliance to battle the Empire and save the galaxy." },
      // { id: "0041", title: "Jurassic Park", image: "media/jurassic-park.png", summary: "Dinosaurs roam again in Spielberg’s thrilling adventure about science, greed, and survival." },
      // { id: "0042", title: "Gladiator", image: "media/gladiator.png", summary: "A betrayed Roman general seeks vengeance and honor in Ridley Scott’s epic." },
      // { id: "0043", title: "Goodfellas", image: "media/goodfellas.png", summary: "Scorsese’s gangster saga follows Henry Hill’s rise and fall in the mob." },
      // { id: "0044", title: "Casablanca", image: "media/casablanca.png", summary: "A nightclub owner faces love and sacrifice in wartime Morocco." },
      // { id: "0045", title: "The Silence of the Lambs", image: "media/silence-lambs.png", summary: "Clarice Starling seeks help from Hannibal Lecter to catch a serial killer." },
      // { id: "0046", title: "Parasite", image: "media/parasite.png", summary: "A poor family infiltrates a wealthy household, exposing class divides and hidden secrets." },
      // { id: "0047", title: "La La Land", image: "media/lala-land.png", summary: "A jazz musician and aspiring actress chase dreams and romance in Los Angeles." },
      // { id: "0048", title: "The Social Network", image: "media/social-network.png", summary: "The rise of Facebook sparks ambition, betrayal, and legal battles." },
      // { id: "0049", title: "Whiplash", image: "media/whiplash.png", summary: "A young drummer faces brutal mentorship in pursuit of greatness." },
    ],
    
    tv: [
      { id: "0006", title: "Breaking Bad", image: "media/breaking-bad.jpg", summary: "A high-school chemistry teacher turns to making meth after a cancer diagnosis, transforming into a ruthless criminal." },
      { id: "0007", title: "Stranger Things", image: "media/stranger-things.jpg", summary: "A group of kids uncovers supernatural forces and secret experiments after their friend mysteriously disappears." },
      { id: "0019", title: "Chernobyl", image: "media/chernobyl.jpg", summary: "A dramatization of the 1986 nuclear disaster, revealing the human cost and heroism behind preventing an even greater catastrophe." },
      { id: "0002", title: "The Last of Us", image: "media/the-last-of-us.png", summary: "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope." },
      { id: "0020", title: "Avatar: The Last Airbender", image: "media/atla.jpg", summary: "Aang must master the elements and defeat the Fire Nation to restore peace to a war-torn world." },
      { id: "0021", title: "Game of Thrones", image: "media/game-of-thrones.jpg", summary: "Noble houses clash for control of the Iron Throne as ancient threats rise beyond the realm’s borders." },
      { id: "0022", title: "Attack on Titan", image: "media/attack-on-titan.jpg", summary: "Humanity’s last survivors battle towering man-eating Titans while uncovering shocking truths about their world." },
      { id: "0023", title: "Rick and Morty", image: "media/rick-and-morty.jpg", summary: "A reckless genius scientist drags his grandson through bizarre, dangerous adventures across time and space." },

      // These need images still:
      // { id: "0050", title: "The Sopranos", image: "media/sopranos.png", summary: "Tony Soprano balances mob life with family struggles in HBO’s groundbreaking drama." },
      // { id: "0051", title: "Friends", image: "media/friends.png", summary: "Six friends navigate love, careers, and comedy in New York City." },
      // { id: "0052", title: "The Office", image: "media/office.png", summary: "A mockumentary about quirky employees at Dunder Mifflin Paper Company." },
      // { id: "0053", title: "The Wire", image: "media/wire.png", summary: "Baltimore’s drug trade is explored through cops, dealers, and institutions." },
      // { id: "0054", title: "Seinfeld", image: "media/seinfeld.png", summary: "A sitcom about nothing, following Jerry and friends’ everyday misadventures." },
      // { id: "0055", title: "The Crown", image: "media/crown.png", summary: "A dramatization of Queen Elizabeth II’s reign and the British monarchy." },
      // { id: "0056", title: "Lost", image: "media/lost.png", summary: "Plane crash survivors face mysteries on a strange island." },
      // { id: "0057", title: "Mad Men", image: "media/mad-men.png", summary: "Advertising executives navigate ambition and identity in 1960s New York." },
      // { id: "0058", title: "Better Call Saul", image: "media/better-call-saul.png", summary: "The origin story of lawyer Jimmy McGill, who becomes Saul Goodman." },
      // { id: "0059", title: "Westworld", image: "media/westworld.png", summary: "A futuristic theme park of androids spirals into chaos and rebellion." },
      // { id: "0060", title: "The Mandalorian", image: "media/mandalorian.png", summary: "A lone bounty hunter protects a mysterious child in the Star Wars universe." },
      // { id: "0061", title: "Succession", image: "media/succession.png", summary: "The Roy family battles for control of a global media empire." },
      // { id: "0062", title: "House of the Dragon", image: "media/house-dragon.png", summary: "The Targaryen dynasty faces civil war in Westeros centuries before Game of Thrones." },
      // { id: "0063", title: "The Boys", image: "media/the-boys.png", summary: "A group of vigilantes fights corrupt superheroes in a darkly satirical world." },
      // { id: "0064", title: "Peaky Blinders", image: "media/peaky-blinders.png", summary: "A gangster family rises in post-WWI Birmingham, England." },
    ],
    
    games: [
      { id: "0008", title: "Elden Ring", image: "media/elden-ring.jpg", summary: "In the Lands Between, a Tarnished warrior journeys to restore the shattered Elden Ring and become Elden Lord." },
      { id: "0009", title: "Zelda: Tears of the Kingdom", image: "media/zelda-totk.jpg", summary: "Link explores sky islands and underground depths to stop a spreading darkness that threatens Hyrule." },
      { id: "0024", title: "Red Dead Redemption 2", image: "media/red-dead-2.jpg", summary: "Arthur Morgan navigates loyalty, survival, and the fading Wild West as his outlaw gang begins to crumble." },
      { id: "0025", title: "Where Winds Meet", image: "media/wwm.jpg", summary: "A martial-arts wanderer shapes his destiny in a war-torn ancient China filled with political intrigue." },
      { id: "0003", title: "Cyberpunk 2077", image: "media/cyberpunk-2077.png", summary: "In 2077, America is in pieces. Megacorps control life in all its aspects from the top floors of their sky-high fortresses. Down below, drug-pushing gangs, dirty-tech hustlers, and slingers of illicit braindances run the streets. The world in between is where decadence, sex, and pop culture mix with violent crime, extreme poverty, and the unattainable promise of the American Dream. In Cyberpunk 2077 you play as V-a hired gun on the rise and you just got your first serious contract. In a world of cyberenhanced street warriors, tech-savvy netrunners, and corporate lifehackers, today you take your first step towards becoming an urban legend." },
      { id: "0026", title: "Baldur's Gate 3", image: "media/baldurs-3.jpg", summary: "A group of heroes infected with a mind-flayer parasite must fight fate, forge alliances, and shape the future of the realms." },
      { id: "0027", title: "Zelda: Ocarina of Time", image: "media/zelda-ocarina.jpg", summary: "Link travels through time to stop Ganondorf from plunging Hyrule into darkness." },
      { id: "0028", title: "Grand Theft Auto V", image: "media/gta5.jpg", summary: "Three criminals in Los Santos team up for high-stakes heists while dealing with chaos in their personal lives." },

      // These need images still:
      // { id: "0065", title: "The Witcher 3: Wild Hunt", image: "media/witcher3.png", summary: "Geralt of Rivia searches for his adopted daughter amid war and monsters." },
      // { id: "0066", title: "Halo: Combat Evolved", image: "media/halo.png", summary: "Master Chief battles the Covenant in humanity’s fight for survival." },
      // { id: "0067", title: "Final Fantasy VII", image: "media/ff7.png", summary: "Cloud Strife joins a rebellion against a corrupt corporation and faces destiny." },
      // { id: "0068", title: "Pokémon Red/Blue", image: "media/pokemon.png", summary: "Players capture and train Pokémon to become champions." },
      // { id: "0069", title: "Dark Souls", image: "media/dark-souls.png", summary: "A punishing action RPG where players battle through a cursed world." },
      // { id: "0070", title: "Resident Evil 4", image: "media/re4.png", summary: "Leon Kennedy battles cultists and monsters to rescue the president’s daughter." },
      // { id: "0071", title: "Super Mario Bros.", image: "media/mario.png", summary: "Mario and Luigi battle Bowser to rescue Princess Peach." },
      // { id: "0072", title: "Minecraft", image: "media/minecraft.png", summary: "A sandbox world where players build, explore, and survive." },
      // { id: "0073", title: "Overwatch", image: "media/overwatch.png", summary: "Team-based hero shooter with diverse characters and abilities." },
      // { id: "0074", title: "Fortnite", image: "media/fortnite.png", summary: "Battle royale game where players fight to be the last standing." },
      // { id: "0075", title: "Call of Duty: Modern Warfare", image: "media/cod-mw.png", summary: "Military shooter with intense campaigns and multiplayer battles." },
      // { id: "0076", title: "Hades", image: "media/hades.png", summary: "Zagreus battles through the Underworld in this roguelike steeped in Greek mythology." },
      // { id: "0077", title: "Sekiro: Shadows Die Twice", image: "media/sekiro.png", summary: "A shinobi fights to rescue his lord in Sengoku-era Japan." },
      // { id: "0078", title: "Mass Effect 2", image: "media/mass-effect2.png", summary: "Commander Shepard recruits a team to stop a galactic threat." },
      // { id: "0079", title: "Portal 2", image: "media/portal2.png", summary: "Players solve puzzles with a portal gun in a witty, mind-bending adventure." },
    ],
  
    music: [
      { id: "0010", title: "The Beatles - Abbey Road", image: "media/the-beatles-abbey-road.jpg", summary: "A landmark album blending rock, harmony, and experimental sound, showcasing the band’s evolution." },
      { id: "0011", title: "Taylor Swift - 1989", image: "media/taylor-swift-1989.jpg", summary: "A synth-pop reinvention exploring themes of independence, love, and self-discovery." },
      { id: "0029", title: "Coldplay - Viva La Vida", image: "media/viva-la-vida.jpg", summary: "An orchestral pop album reflecting on power, loss, and redemption through vivid storytelling." },
      { id: "0030", title: "Queen - Bohemian Rhapsody", image: "media/bohemian-rapsody.jpg", summary: "A dramatic, operatic rock classic that delves into inner conflict and emotional release." },
      { id: "0031", title: "Michael Jackson - Bad", image: "media/bad.jpg", summary: "A high-energy pop album driven by confidence, catchy hooks, and groundbreaking production." },
      { id: "0032", title: "One Republic - Counting Stars", image: "media/counting-stars.jpg", summary: "A rhythmic pop track about chasing dreams while wrestling with the pressures of life." },
      { id: "0033", title: "Bastille - Pompeii", image: "media/pompeii.jpg", summary: "An upbeat anthem that uses ancient imagery to explore themes of regret and reflection." },
      { id: "0034", title: "The Neighbourhood - Sweater Weather", image: "media/sweater-weather.jpg", summary: "A moody indie-pop song centered on intimacy, comfort, and emotional vulnerability." },

      // These need images still:
      // { id: "0080", title: "Nirvana - Nevermind", image: "media/nevermind.png", summary: "Grunge classic featuring 'Smells Like Teen Spirit,' reshaping rock in the 1990s." },
      // { id: "0081", title: "Adele - 21", image: "media/adele-21.png", summary: "Soulful ballads of heartbreak and resilience, including 'Rolling in the Deep' and 'Someone Like You'." },
      // { id: "0082", title: "Kendrick Lamar - To Pimp a Butterfly", image: "media/to-pimp-a-butterfly.png", summary: "A politically charged hip-hop masterpiece blending jazz, funk, and social commentary." },
      // { id: "0083", title: "Fleetwood Mac - Rumours", image: "media/rumours.png", summary: "Iconic rock album born from personal turmoil, featuring 'Go Your Own Way' and 'Dreams'." },
      // { id: "0084", title: "Pink Floyd - The Dark Side of the Moon", image: "media/dark-side.png", summary: "A psychedelic rock landmark exploring time, money, and existential themes." },
      // { id: "0085", title: "Beyoncé - Lemonade", image: "media/lemonade.png", summary: "A genre-blending visual album tackling infidelity, empowerment, and Black identity." },
      // { id: "0086", title: "Radiohead - OK Computer", image: "media/ok-computer.png", summary: "Experimental rock album critiquing modern alienation and technology." },
      // { id: "0087", title: "Prince - Purple Rain", image: "media/purple-rain.png", summary: "A fusion of rock, R&B, and funk, cementing Prince’s legacy as a musical innovator." },
      // { id: "0088", title: "Bob Dylan - Highway 61 Revisited", image: "media/highway-61.png", summary: "Folk-rock classic featuring 'Like a Rolling Stone,' redefining popular music." },
      // { id: "0089", title: "The Rolling Stones - Exile on Main St.", image: "media/exile.png", summary: "A gritty double album blending rock, blues, and soul." },
      // { id: "0090", title: "David Bowie - The Rise and Fall of Ziggy Stardust", image: "media/ziggy.png", summary: "A glam rock concept album about an alien rock star." },
      // { id: "0091", title: "U2 - The Joshua Tree", image: "media/joshua-tree.png", summary: "An arena rock album exploring spirituality, politics, and Americana." },
      // { id: "0092", title: "Madonna - Like a Prayer", image: "media/like-a-prayer.png", summary: "Pop album mixing religious imagery with personal storytelling." },
      // { id: "0093", title: "Bruce Springsteen - Born to Run", image: "media/born-to-run.png", summary: "An anthem-filled rock album capturing youthful dreams and escape." },
      // { id: "0094", title: "Dr. Dre - 2001", image: "media/dr-dre-2001.png", summary: "West Coast hip-hop classic defining the G-funk era." },
    ],
  
    books: [
      { id: "1001", title: "Lonesome Dove", image: "media/lonesome-dove.png", summary: "Larry McMurtry’s Lonesome Dove is an epic Western about two retired Texas Rangers, Augustus McCrae and Woodrow Call, who embark on a perilous cattle drive from Texas to Montana, confronting love, loss, and the harsh realities of frontier life." },
      { id: "1002", title: "The Nickel Boys", image: "media/the-nickel-boys.png", summary: "Colson Whitehead’s The Nickel Boys tells the harrowing story of Elwood Curtis, a Black teenager sent to a brutal reform school in 1960s Florida, exposing the systemic racism and abuse hidden behind its walls." },
      { id: "1003", title: "Shogun", image: "media/shogun.png", summary: "James Clavell’s Shōgun (1975) follows English navigator John Blackthorne, shipwrecked in feudal Japan, who becomes entangled in samurai honor, political intrigue, and cultural transformation as he aids the ambitious daimyo Lord Toranaga in his rise to power." },
      { id: "1004", title: "American Gods", image: "media/american-gods.png", summary: "Neil Gaiman’s American Gods (2001) follows Shadow Moon, an ex-con who becomes bodyguard to the mysterious Mr. Wednesday, and is drawn into a mythic battle between the fading old gods brought to America by immigrants and the rising new gods of modern technology, media, and globalization." },
      { id: "1005", title: "The Three-Body Problem", image: "media/the-three-body-problem.png", summary: "Liu Cixin’s The Three-Body Problem (2008) is a hard science fiction novel in which humanity first makes contact with an alien civilization from the unstable planet Trisolaris, sparking a secret struggle between those who welcome the aliens as saviors and those who prepare to resist their invasion." },
      { id: "1006", title: "Dune", image: "media/dune.jpg", summary: "Paul Atreides becomes entangled in political betrayal and prophetic destiny on the desert planet Arrakis." },
      { id: "1007", title: "1984", image: "media/1984.jpg", summary: "A man struggles to hold onto truth and identity under a totalitarian regime that controls every thought." },
      { id: "1008", title: "The Great Gatsby", image: "media/tgg.jpg", summary: "A mysterious millionaire’s pursuit of love reveals the illusions and decadence of the Jazz Age." },
      { id: "1009", title: "The Catcher in the Rye", image: "media/catcher-rye.jpg", summary: "Holden Caulfield wanders New York, wrestling with loneliness, growing up, and finding authenticity." },
      { id: "1010", title: "To Kill a Mockingbird", image: "media/tkamb.jpg", summary: "A young girl witnesses racial injustice in her Southern town as her father defends an innocent man." },
      { id: "1011", title: "Moby-Dick", image: "media/moby-dick.png", summary: "Captain Ahab obsessively hunts the white whale Moby Dick, exploring themes of obsession, fate, and humanity’s struggle against nature." },
      { id: "1012", title: "Pride and Prejudice", image: "media/pride-prejudice.jpg", summary: "Jane Austen’s classic romance where Elizabeth Bennet navigates love, class, and misunderstandings with the enigmatic Mr. Darcy." },
      { id: "1013", title: "The Lord of the Rings", image: "media/lotr.jpg", summary: "Frodo Baggins embarks on a perilous quest to destroy the One Ring and save Middle-earth from darkness." },
      { id: "1014", title: "Harry Potter and the Sorcerer’s Stone", image: "media/harry-potter-1.jpg", summary: "A young boy discovers he is a wizard and begins his journey at Hogwarts, facing magical wonders and dangers." },
      { id: "1015", title: "The Hobbit", image: "media/hobbit.jpg", summary: "Bilbo Baggins is swept into an adventure with dwarves and a wizard, confronting dragons, treasure, and courage." },
      { id: "1016", title: "Frankenstein", image: "media/frankenstein.jpg", summary: "Victor Frankenstein creates a living being, only to face tragic consequences in this tale of ambition and responsibility." },
      { id: "1017", title: "Dracula", image: "media/dracula.jpg", summary: "Bram Stoker’s gothic horror where Count Dracula seeks to spread his vampiric curse, opposed by a band of determined allies." },
      { id: "1018", title: "The Odyssey", image: "media/odyssey.jpg", summary: "Homer’s epic poem recounts Odysseus’s long journey home from Troy, filled with gods, monsters, and trials of endurance." },
      { id: "1019", title: "Crime and Punishment", image: "media/crime-punishment.jpg", summary: "Fyodor Dostoevsky’s psychological novel about Raskolnikov, a man who commits murder and wrestles with guilt and redemption." },
      { id: "1020", title: "War and Peace", image: "media/war-peace.jpg", summary: "Leo Tolstoy’s sweeping epic intertwines personal lives with the Napoleonic wars, exploring love, fate, and history." },
      { id: "1021", title: "Les Misérables", image: "media/les-miserables.jpg", summary: "Victor Hugo’s masterpiece follows Jean Valjean’s quest for redemption amid revolution, injustice, and compassion in 19th-century France." },
      { id: "1022", title: "The Alchemist", image: "media/alchemist.jpg", summary: "Paulo Coelho’s allegorical novel about Santiago, a shepherd who pursues his personal legend and discovers life’s deeper meaning." },
      { id: "1023", title: "Brave New World", image: "media/brave-new-world.jpg", summary: "A dystopian future where society is engineered for stability, raising questions of freedom, individuality, and control." },
      { id: "1024", title: "The Road", image: "media/the-road.jpg", summary: "Cormac McCarthy’s haunting tale of a father and son journeying through a post-apocalyptic wasteland, clinging to hope." },
      { id: "1025", title: "The Handmaid’s Tale", image: "media/handmaids-tale.jpg", summary: "Margaret Atwood’s dystopian novel where women are subjugated in Gilead, told through the eyes of Offred, a Handmaid." },
    ],
  } 
};

